import { Rubik } from "next/font/google";
import "react-perfect-scrollbar/dist/css/styles.css";
import "/public/css/style.css";
import { AuthProvider } from "@/contexts/AuthContext";

const rubik = Rubik({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Aermint ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/favicon.png" sizes="16" />
      <body className={rubik.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
